function createfigure(X1, YMatrix1, VSF_CF1, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, VSF_CF1, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  VSF_CF1:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 22-Jan-2020 11:26:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineStyle','--');
set(plot1(1),'DisplayName','Intact_experimental',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(plot1(2),'DisplayName','VSF_experimental',...
    'Color',[1 0.843137264251709 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(VSF_CF1,YMatrix2,'LineWidth',2);
set(plot2(1),'DisplayName','VSD_simulated');
set(plot2(2),'DisplayName','Intact_simulated');

% Create ylabel
ylabel(' GRFv (N)');

% Create xlabel
xlabel(' Time (s)');

% Create title
title(' ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 3.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-500 2500]);
box(axes1,'on');
% Create legend
legend(axes1,'show');

